### ISSUE TITLE
13. Update air quality index

### ISSUE THREAD

**Issue by awunderground** [UI-Research/mobility-from-poverty#211]
Pillar: Healthy Environment and Access to Good Health Care
Predictor: Environmental Quality
Metric: Air quality index

- [ ] Rename to `index_aqi` & `index_aqi_quality` 
- [ ] Add 2021 data

**Comment by awunderground** [comment]
On second thought, I think we need a different name than `index_air_quality`. `_quality` should be reserved for the quality variables.

**Comment by tinatinc** [comment]
Making a note that I have updated naming instructions above (we want the variable names to be `index_aqi_quality` &  `index_aqi_quality` )

**Comment by awunderground** [comment]
PR is #247

**Comment by awunderground** [comment]
Closed with #247
