### ISSUE TITLE
14. Update rates of reported violent crime and property crime

### ISSUE THREAD

**Issue by awunderground** [UI-Research/mobility-from-poverty#212]
Pillar: Responsible and Just Governance
Predictor: Safety from Crime
Metric: Reported property crimes per 100,000 people and reported violent crimes per 100,000 people

- [ ] Rename to `rate_violent_crime`, `rate_property_crime`, and `rate_violent_crime_quality`, `rate_property_crime_quality`
- [ ] Add 2022 data

**Comment by vpancini** [comment]
The data for this come from ICPSR. To access the data, users must (1) create an account, (2) log in, and (3) agree to the terms of use. In this case, it is more trouble than it’s worth to try to figure out how to download the data via code. We download the data manually instead.

**Comment by tinatinc** [comment]
Note that I have updated the to-do to reflect that we want there to be a quality variable assigned to each of the two metric values, not one overall (previously this read `rate_crime_quality` for both)

**Comment by awunderground** [comment]
Closed with #293
