### ISSUE TITLE
15. Update rate of juvenile justice arrests

### ISSUE THREAD

**Issue by awunderground** [UI-Research/mobility-from-poverty#213]
Pillar: Responsible and Just Governance
Predictor: Just Policing
Metric: Juvenile arrests per 100,000 juveniles

- [ ] Rename to `rate_juv_arrest` and `rate_juv_arrest_quality`
- [ ] ***Updated** Add gender:  subgroup_type = gender; subgroup= All, Male, Female; Add age: subgroup_type = age; subgroup= All, Age 9 and younger, Age 10 to 12, Age 13 to 15, Age 16 to 17; 
- [ ] Add 2022 data

**Comment by vpancini** [comment]
The data for this come from ICPSR. To access the data, users must (1) create an account, (2) log in, and (3) agree to the terms of use. In this case, it is more trouble than it’s worth to try to figure out how to download the data via code. We download the data manually instead.

**Comment by tinatinc** [comment]
Note that I have updated the original To-Do comment to specify the subgroup names and buckets desired

**Comment by awunderground** [comment]
PR is #288

**Comment by awunderground** [comment]
Closed with #295
